version: '3'
services:
  mysql:
      image: "mysql"
      environment:
        - MYSQL_ROOT_PASSWORD=password
  web:
    image: "wordpress"
    environment:
            - WORDPRESS_DB_PASSWORD=password
    ports:
      - "8080:80"